rule_files:
  - /prometheus/rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'application_camel_context_exchanges_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="cbvn81m9fbo9fmh5rn60"}'
        values: '1+1x249'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="cbvn81m9fbo9fmh5rn60"}'
        values: '0+0x249'

      - series: 'application_camel_context_exchanges_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccbpo0absr9v601smbhg"}'
        values: '1+1x249'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccbpo0absr9v601smbhg"}'
        values: '0+0x249'

      - series: 'application_camel_context_exchanges_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccqpe7g8sdu754v02vn0"}'
        values: '1+1x249'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccqpe7g8sdu754v02vn0"}'
        values: '0+0x244 1+1x4'

      - series: 'application_camel_context_exchanges_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccqkkc33ts1p3ohhbq9g"}'
        values: '1+1x249'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cafmth1l8123ida8obm0", cos_connector_id="ccqkkc33ts1p3ohhbq9g"}'
        values: '0+0x249'

      - series: 'application_camel_context_exchanges_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="ce7l55u5fmgas4qav990"}'
        values: '1+1x1000'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="ce7l55u5fmgas4qav990"}'
        values: '0+0x1000'

    promql_expr_test:
      # recordings used in tested alerts, for clarity
      - expr: slo_connector_data_failure_rate:ratio_rate5m
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate5m{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 0.25
          - labels: 'slo_connector_data_failure_rate:ratio_rate5m{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_data_failure_rate:ratio_rate1h
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate1h{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 2.0833333333333336E-02
          - labels: 'slo_connector_data_failure_rate:ratio_rate1h{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_data_failure_rate:ratio_rate30m
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate30m{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 4.166666666666667E-02
          - labels: 'slo_connector_data_failure_rate:ratio_rate30m{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_data_failure_rate:ratio_rate2h
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate2h{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 1.0416666666666668E-02
          - labels: 'slo_connector_data_failure_rate:ratio_rate2h{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_data_failure_rate:ratio_rate24h
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate24h{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 4.999999999999999E-03
          - labels: 'slo_connector_data_failure_rate:ratio_rate24h{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_data_failure_rate:ratio_rate3d
        eval_time: 249m
        exp_samples:
          - labels: 'slo_connector_data_failure_rate:ratio_rate3d{cluster_id="cafmth1l8123ida8obm0", tenant="rhoc"}'
            value: 4.999999999999999E-03
          - labels: 'slo_connector_data_failure_rate:ratio_rate3d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0