rule_files:
  - /prometheus/rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'up{container="cos-fleetshard-operator-camel", cluster_id="cafmth1l8123ida8obm0"}'
        values: '1+0x30 0+0x30 1+0x120'
      - series: 'up{container="cos-fleetshard-operator-camel", cluster_id="cchi5bvod5s2tjbeh7ag"}'
        values: '1+0x180'
      - series: 'up{container="cos-fleetshard-operator-camel", cluster_id="ce85sscmo9pbcfol9e9g"}'
        values: '1+0x60 0+0x60 1+0x60'
      - series: 'up{container="cos-fleetshard-operator-camel", cluster_id="ce8q91ug0sma721hcokg"}'
        values: '1+0x90 0+0x30 1+0x60'

      - series: 'kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel", cluster_id="cafmth1l8123ida8obm0"}'
        values: '0+0x30 1+1x30 0+0x180'
      - series: 'kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel", cluster_id="cchi5bvod5s2tjbeh7ag"}'
        values: '0+0x240'
      - series: 'kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel", cluster_id="ce85sscmo9pbcfol9e9g"}'
        values: '0+0x60 1+1x60 0+0x120'
      - series: 'kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel", cluster_id="ce8q91ug0sma721hcokg"}'
        values: '0+0x120 1+1x30 0+0x90'

    alert_rule_test:
      # CosFleetShardOperatorCamelTargetDown test units
      - eval_time: 10m
        alertname: CosFleetShardOperatorCamelTargetDown
        exp_alerts: [ ]
      - eval_time: 50m
        alertname: CosFleetShardOperatorCamelTargetDown
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelTargetDown
              severity: critical
              cluster_id: cafmth1l8123ida8obm0
            exp_annotations:
              summary: |
                the fleetshard-camel operator is down in cluster: cafmth1l8123ida8obm0
              description: |
                prometheus was unable to scrape the fleetshard-camel operator in the cluster: cafmth1l8123ida8obm0 for longer than 10 minutes.
                This most likely means that the fleetshard-camel operator pod is unable to start
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 80m
        alertname: CosFleetShardOperatorCamelTargetDown
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelTargetDown
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the fleetshard-camel operator is down in cluster: ce85sscmo9pbcfol9e9g
              description: |
                prometheus was unable to scrape the fleetshard-camel operator in the cluster: ce85sscmo9pbcfol9e9g for longer than 10 minutes.
                This most likely means that the fleetshard-camel operator pod is unable to start
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 115m
        alertname: CosFleetShardOperatorCamelTargetDown
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelTargetDown
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the fleetshard-camel operator is down in cluster: ce85sscmo9pbcfol9e9g
              description: |
                prometheus was unable to scrape the fleetshard-camel operator in the cluster: ce85sscmo9pbcfol9e9g for longer than 10 minutes.
                This most likely means that the fleetshard-camel operator pod is unable to start
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
          - exp_labels:
              alertname: CosFleetShardOperatorCamelTargetDown
              severity: critical
              cluster_id: ce8q91ug0sma721hcokg
            exp_annotations:
              summary: |
                the fleetshard-camel operator is down in cluster: ce8q91ug0sma721hcokg
              description: |
                prometheus was unable to scrape the fleetshard-camel operator in the cluster: ce8q91ug0sma721hcokg for longer than 10 minutes.
                This most likely means that the fleetshard-camel operator pod is unable to start
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 150m
        alertname: CosFleetShardOperatorCamelTargetDown
        exp_alerts: []

      # CosFleetShardOperatorCamelContainerFrequentlyRestarting test units
      - eval_time: 10m
        alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
        exp_alerts: [ ]
      - eval_time: 50m
        alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
              severity: critical
              cluster_id: cafmth1l8123ida8obm0
            exp_annotations:
              summary: |
                the fleetshard-camel operator is restarting frequently in cluster: cafmth1l8123ida8obm0
              description: |
                in the previous 60 minutes, the fleetshard-camel operator restarted frequently(more than 3 times)
                in cluster: cafmth1l8123ida8obm0
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 130m
        alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the fleetshard-camel operator is restarting frequently in cluster: ce85sscmo9pbcfol9e9g
              description: |
                in the previous 60 minutes, the fleetshard-camel operator restarted frequently(more than 3 times)
                in cluster: ce85sscmo9pbcfol9e9g
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 160m
        alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the fleetshard-camel operator is restarting frequently in cluster: ce85sscmo9pbcfol9e9g
              description: |
                in the previous 60 minutes, the fleetshard-camel operator restarted frequently(more than 3 times)
                in cluster: ce85sscmo9pbcfol9e9g
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
          - exp_labels:
              alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce8q91ug0sma721hcokg
            exp_annotations:
              summary: |
                the fleetshard-camel operator is restarting frequently in cluster: ce8q91ug0sma721hcokg
              description: |
                in the previous 60 minutes, the fleetshard-camel operator restarted frequently(more than 3 times)
                in cluster: ce8q91ug0sma721hcokg
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 230m
        alertname: CosFleetShardOperatorCamelContainerFrequentlyRestarting
        exp_alerts: [ ]