rule_files:
  - /prometheus/rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'cos_fleetshard_sync_connector_state_count_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="cbvn81m9fbo9fmh5rn60", cos_connector_state="ready"}'
        values: '1+1x8639'

      - series: 'cos_fleetshard_sync_connector_state_count_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="cbvn81m9fbo9fmh5rn61", cos_connector_state="ready"}'
        values: '1+1x4319'
      - series: 'cos_fleetshard_sync_connector_state_count_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="cbvn81m9fbo9fmh5rn61", cos_connector_state="failed_but_ready"}'
        values: '0+0x4319 1+1x4319'

      - series: 'cos_fleetshard_sync_connector_state_count_total{cluster_id="cchi5bvod5s2tjbeh7ag", cos_connector_id="cbvn81m9fbo9fmh5rn62", cos_connector_state="ready"}'
        values: '1+1x8639'

      - series: 'application_camel_context_exchanges_completed_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn60"}'
        values: '1+1x8639'
      - series: 'application_camel_context_exchanges_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn60"}'
        values: '1+1x8639'

      - series: 'application_camel_context_exchanges_completed_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn61"}'
        values: '1+1x4319'
      - series: 'application_camel_context_exchanges_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn61"}'
        values: '1+1x8639'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn61"}'
        values: '0+0x4319 1+1x4319'

      - series: 'application_camel_context_exchanges_completed_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn62"}'
        values: '1+1x8639'
      - series: 'application_camel_context_exchanges_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn62"}'
        values: '1+1x8639'
      - series: 'application_camel_context_exchanges_failed_total{cluster_id="cchi5bvod5s2tjbeh7ag", connector_id="cbvn81m9fbo9fmh5rn62"}'
        values: '0+0x4319'

    promql_expr_test:
      #Testing Availability SLO
      - expr: slo_connector_availability_success_rate:ratio_rate7d
        eval_time: 4319m
        exp_samples:
          - labels: 'slo_connector_availability_success_rate:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 1
      - expr: slo_connector_availability_success_rate:ratio_rate7d
        eval_time: 6d
        exp_samples:
          - labels: 'slo_connector_availability_success_rate:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 8.33333331472789E-01
      - expr: slo_connector_availability_success_rate:ratio_rate28d
        eval_time: 7d
        exp_samples:
          - labels: 'slo_connector_availability_success_rate:ratio_rate28d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 8.333349398047781E-01
      - expr: slo_connector_availability_remaining_error_budget:ratio_rate28d
        eval_time: 4319m
        exp_samples:
          - labels: 'slo_connector_availability_remaining_error_budget:ratio_rate28d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 1
      - expr: slo_connector_availability_remaining_error_budget:ratio_rate7d
        eval_time: 4319m
        exp_samples:
          - labels: 'slo_connector_availability_remaining_error_budget:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 1
      - expr: slo_connector_availability_remaining_error_budget:ratio_rate28d
        eval_time: 7d
        exp_samples:
          - labels: 'slo_connector_availability_remaining_error_budget:ratio_rate28d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      - expr: slo_connector_availability_remaining_error_budget:ratio_rate7d
        eval_time: 6d
        exp_samples:
          - labels: 'slo_connector_availability_remaining_error_budget:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0
      #Testing Data Process SLO
      - expr: slo_connector_data_success_rate:ratio_rate28d
        eval_time: 7d
        exp_samples:
          - labels: 'slo_connector_data_success_rate:ratio_rate28d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 8.333429778369307E-01
      - expr: slo_connector_data_success_rate:ratio_rate7d
        eval_time: 4319m
        exp_samples:
          - labels: 'slo_connector_data_success_rate:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 1
      - expr: slo_connector_data_remaining_error_budget:ratio_rate28d
        eval_time: 4319m
        exp_samples:
          - labels: 'slo_connector_data_remaining_error_budget:ratio_rate28d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 1
      - expr: slo_connector_data_remaining_error_budget:ratio_rate7d
        eval_time: 6d
        exp_samples:
          - labels: 'slo_connector_data_remaining_error_budget:ratio_rate7d{cluster_id="cchi5bvod5s2tjbeh7ag", tenant="rhoc"}'
            value: 0