rule_files:
  - /prometheus/rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'up{container="strimzi-cluster-operator", cluster_id="cafmth1l8123ida8obm0"}'
        values: '1+0x30 0+0x30 1+0x120'
      - series: 'up{container="strimzi-cluster-operator", cluster_id="cchi5bvod5s2tjbeh7ag"}'
        values: '1+0x180'
      - series: 'up{container="strimzi-cluster-operator", cluster_id="ce85sscmo9pbcfol9e9g"}'
        values: '1+0x60 0+0x60 1+0x60'
      - series: 'up{container="strimzi-cluster-operator", cluster_id="ce8q91ug0sma721hcokg"}'
        values: '1+0x90 0+0x30 1+0x60'

      - series: 'kube_pod_container_status_restarts_total{container="strimzi-cluster-operator", cluster_id="cafmth1l8123ida8obm0"}'
        values: '0+0x30 1+1x30 0+0x180'
      - series: 'kube_pod_container_status_restarts_total{container="strimzi-cluster-operator", cluster_id="cchi5bvod5s2tjbeh7ag"}'
        values: '0+0x240'
      - series: 'kube_pod_container_status_restarts_total{container="strimzi-cluster-operator", cluster_id="ce85sscmo9pbcfol9e9g"}'
        values: '0+0x60 1+1x60 0+0x120'
      - series: 'kube_pod_container_status_restarts_total{container="strimzi-cluster-operator", cluster_id="ce8q91ug0sma721hcokg"}'
        values: '0+0x120 1+1x30 0+0x90'

    alert_rule_test:
      # StrimziOperatorTargetDown test units
      - eval_time: 10m
        alertname: StrimziOperatorTargetDown
        exp_alerts: [ ]
      - eval_time: 50m
        alertname: StrimziOperatorTargetDown
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorTargetDown
              severity: critical
              cluster_id: cafmth1l8123ida8obm0
            exp_annotations:
              summary: 'the strimzi-cluster-operator target is down'
              description: |
                prometheus has been unable to scrape the strimzi-cluster-operator pod in the
                cluster: cafmth1l8123ida8obm0 for longer than 10 minutes
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 80m
        alertname: StrimziOperatorTargetDown
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorTargetDown
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: 'the strimzi-cluster-operator target is down'
              description: |
                prometheus has been unable to scrape the strimzi-cluster-operator pod in the
                cluster: ce85sscmo9pbcfol9e9g for longer than 10 minutes
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 115m
        alertname: StrimziOperatorTargetDown
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorTargetDown
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: 'the strimzi-cluster-operator target is down'
              description: |
                prometheus has been unable to scrape the strimzi-cluster-operator pod in the
                cluster: ce85sscmo9pbcfol9e9g for longer than 10 minutes
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
          - exp_labels:
              alertname: StrimziOperatorTargetDown
              severity: critical
              cluster_id: ce8q91ug0sma721hcokg
            exp_annotations:
              summary: 'the strimzi-cluster-operator target is down'
              description: |
                prometheus has been unable to scrape the strimzi-cluster-operator pod in the
                cluster: ce8q91ug0sma721hcokg for longer than 10 minutes
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 150m
        alertname: StrimziOperatorTargetDown
        exp_alerts: []

      # StrimziOperatorContainerFrequentlyRestarting test units
      - eval_time: 10m
        alertname: StrimziOperatorContainerFrequentlyRestarting
        exp_alerts: [ ]
      - eval_time: 50m
        alertname: StrimziOperatorContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorContainerFrequentlyRestarting
              severity: critical
              cluster_id: cafmth1l8123ida8obm0
            exp_annotations:
              summary: |
                the strimzi-cluster-operator pod is restarting frequently in cluster: cafmth1l8123ida8obm0
              description: 'the strimzi-cluster-operator container restarted frequently in the last 60 minutes'
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 130m
        alertname: StrimziOperatorContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the strimzi-cluster-operator pod is restarting frequently in cluster: ce85sscmo9pbcfol9e9g
              description: 'the strimzi-cluster-operator container restarted frequently in the last 60 minutes'
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 160m
        alertname: StrimziOperatorContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: StrimziOperatorContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce85sscmo9pbcfol9e9g
            exp_annotations:
              summary: |
                the strimzi-cluster-operator pod is restarting frequently in cluster: ce85sscmo9pbcfol9e9g
              description: 'the strimzi-cluster-operator container restarted frequently in the last 60 minutes'
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
          - exp_labels:
              alertname: StrimziOperatorContainerFrequentlyRestarting
              severity: critical
              cluster_id: ce8q91ug0sma721hcokg
            exp_annotations:
              summary: |
                the strimzi-cluster-operator pod is restarting frequently in cluster: ce8q91ug0sma721hcokg
              description: 'the strimzi-cluster-operator container restarted frequently in the last 60 minutes'
              sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
      - eval_time: 230m
        alertname: StrimziOperatorContainerFrequentlyRestarting
        exp_alerts: [ ]