---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: camel-k-operator-rules
spec:
  groups:
    - name: camel-k-operator
      interval: 10m
      rules:
        - alert: CamelKOperatorTargetDown
          expr: group by (cluster_id) (up{container="camel-k-operator"} !=1 or absent(up{container="camel-k-operator"}))
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'the camel-k operator target is down'
            description: |
              prometheus has been unable to scrape the camel-k operator pod in the
              cluster: {{ $labels.cluster_id }} for longer than 10 minutes
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: CamelKOperatorContainerFrequentlyRestarting
          expr: sum by (cluster_id) (increase(kube_pod_container_status_restarts_total{container="camel-k-operator"}[60m])) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the camel-k operator pod is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: 'the camel-k operator container restarted frequently in the last 60 minutes'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
