---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: rhoc-connectors-slo-rules
spec:
  groups:
    - name: rhoc-connectors-slo-rules
      interval: 1m
      rules:
        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[5m]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[5m]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[5m]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate5m
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[30m]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[30m]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[30m]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate30m
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[1h]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[1h]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[1h]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate1h
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[2h]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[2h]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[2h]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate2h
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[6h]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[6h]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[6h]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate6h
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[12h]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[12h]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[12h]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate12h
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[24h]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[24h]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[24h]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate24h
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[3d]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[3d]))
              +
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[3d]))
            )
          record: slo_connector_availability_failure_rate:ratio_rate3d
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[7d]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[7d]))
              +
              ( sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[7d])) OR on() vector(0) )
            )
          record: slo_connector_availability_success_rate:ratio_rate7d
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[28d]))
            /
            (
              sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[28d]))
              +
              ( sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[28d])) OR on() vector(0) )
            )
          record: slo_connector_availability_success_rate:ratio_rate28d
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id, cos_connector_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="provisioning"}[5m]))
            /
            sum by (cluster_id, cos_connector_id) (rate(cos_fleetshard_sync_connector_state_count_total{}[5m]))
          record: connector_provisioning:ratio_rate5m
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id, cos_connector_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="provisioning"}[30m]))
            /
            sum by (cluster_id, cos_connector_id) (rate(cos_fleetshard_sync_connector_state_count_total{}[30m]))
          record: connector_provisioning:ratio_rate30m
          labels:
            tenant: rhoc

        - expr: |
            clamp_min(
              (
                (
                  0.005 *
                  (
                    sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[28d]))
                    +
                    (
                      sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[28d]))
                      OR
                      on() vector(0)
                    )
                  )
                )
                -
                (sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[28d])) OR on() vector(0))
              ) /
              (
                0.005 *
                (
                  sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[28d]))
                  +
                  (sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[28d])) OR on() vector(0))
                )
              )
            , 0)
          record: slo_connector_availability_remaining_error_budget:ratio_rate28d
          labels:
            tenant: rhoc

        - expr: |
            clamp_min(
              (
                (
                  0.005 *
                  (
                    sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[7d]))
                    +
                    (sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[7d])) OR on() vector(0))
                  )
                )
                -
                (sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[7d])) OR on() vector(0))
              ) /
              (
                0.005 *
                (
                  sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="ready"}[7d]))
                  +
                  (sum by (cluster_id) (rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state="failed_but_ready"}[7d])) OR on() vector(0))
                )
              )
            , 0)
          record: slo_connector_availability_remaining_error_budget:ratio_rate7d
          labels:
            tenant: rhoc

        - expr: |
            clamp_min(
              (
                (
                  (sum by (cluster_id) (rate(application_camel_context_exchanges_total[28d])) * 0.005)
                  -
                  ( sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[28d])) OR on() vector(0) )
                )
                /
                (sum by (cluster_id) (rate(application_camel_context_exchanges_total[28d])) * 0.005)
              )
            , 0)
          record: slo_connector_data_remaining_error_budget:ratio_rate28d
          labels:
            tenant: rhoc

        - expr: |
            clamp_min(
              (
                (
                  (sum by (cluster_id) (rate(application_camel_context_exchanges_total[7d])) * 0.005)
                  -
                  ( sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[7d])) OR on() vector(0) )
                )
                /
                (sum by (cluster_id) (rate(application_camel_context_exchanges_total[7d])) * 0.005)
              )
            , 0)
          record: slo_connector_data_remaining_error_budget:ratio_rate7d
          labels:
            tenant: rhoc

        - expr: |
            sum by (cluster_id) (rate(application_camel_context_exchanges_completed_total[28d]))
            /
            sum by (cluster_id) (rate(application_camel_context_exchanges_total[28d]))
          record: slo_connector_data_success_rate:ratio_rate28d
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_completed_total[7d]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[7d]))
          record: slo_connector_data_success_rate:ratio_rate7d
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[1h]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[1h]))
          record: slo_connector_data_failure_rate:ratio_rate1h
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[5m]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[5m]))
          record: slo_connector_data_failure_rate:ratio_rate5m
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[6h]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[6h]))
          record: slo_connector_data_failure_rate:ratio_rate6h
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[30m]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[30m]))
          record: slo_connector_data_failure_rate:ratio_rate30m
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[3d]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[3d]))
          record: slo_connector_data_failure_rate:ratio_rate3d
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[6h]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[6h]))
          record: slo_connector_data_failure_rate:ratio_rate6h
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[24h]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[24h]))
          record: slo_connector_data_failure_rate:ratio_rate24h
          labels:
            tenant: rhoc

        - expr: |
              sum by (cluster_id) (rate(application_camel_context_exchanges_failed_total[2h]))
              /
              sum by (cluster_id) (rate(application_camel_context_exchanges_total[2h]))
          record: slo_connector_data_failure_rate:ratio_rate2h
          labels:
            tenant: rhoc

        - alert: RHOCConnectorsAvailability5mTo30mLongProvisioning
          expr: |
            (
              connector_provisioning:ratio_rate5m > 0.9
              AND
              connector_provisioning:ratio_rate30m > 0.9
            )
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: |
              the connector {{ $labels.cos_connector_id }} has been in provisioning state for too long
            description: |
              the connector {{ $labels.cos_connector_id }} in cluster {{ $labels.cluster_id }} is in provisioning state for
              longer than 30 minutes but the desired state is ready
            dashboard: |
              https://grafana.app-sre.devshift.net/d/uln0BXC7z/camelk-specific-connectors?orgId=1
            sop_url: https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/rhoc_connectors_availability_provisioning.adoc

        - alert: RHOCConnectorsAvailability5mTo1hOr30mTo6hP2BudgetBurn
          expr: |
            (
              slo_connector_availability_failure_rate:ratio_rate1h > (14.4 * (1 - 0.995)) # burning through 2% of monthly budget  within an hour
              AND
              slo_connector_availability_failure_rate:ratio_rate5m > (14.4 * (1 - 0.995))
              )
              OR
              (
              slo_connector_availability_failure_rate:ratio_rate6h > (6 * (1 - 0.995)) # burning through 5% of monthly budget within 6 hours
              AND
              slo_connector_availability_failure_rate:ratio_rate30m > (6 * (1 - 0.995))
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: 'High 1h/6h Connectors availability budget burn for RHOC (current value: {{ $value | humanize }})'
            description: 'An error budget greater than 2% has been burnt in the last 1h/6h period'
            dashboard: 'https://grafana.app-sre.devshift.net/d/3lmqGVq7z/data-plane-overview?orgId=1'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/connectors_availability_error_budget_burnt.adoc'

        - alert: RHOCConnectorsAvailability2hTo24HOr6hTo3dBudgetBurn
          expr: |
            (
              slo_connector_availability_failure_rate:ratio_rate24h > (3 * (1 - 0.995)) # burning through 2.5% of monthly budget within a day
              AND
              slo_connector_availability_failure_rate:ratio_rate2h > (3 * (1 - 0.995))
              )
              OR
              (
              slo_connector_availability_failure_rate:ratio_rate3d > (1 * (1 - 0.995)) # burning through 10% of monthly budget within 3 days
              AND
              slo_connector_availability_failure_rate:ratio_rate6h > (1 * (1 - 0.995))
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: 'High 3d/24h Connectors availability budget burn for RHOC (current value: {{ $value | humanize }})'
            description: 'An error budget greater than 2.5% has been burnt in the last 1d period or an error budget greater
              than 10% has been burnt in the last 3 days period'
            dashboard: 'https://grafana.app-sre.devshift.net/d/3lmqGVq7z/data-plane-overview?orgId=1'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/connectors_availability_error_budget_burnt.adoc'

        - alert: RHOCConnectorsDataError5mTo1hOr30mTo6hP2BudgetBurn
          expr: |
            (
              slo_connector_data_failure_rate:ratio_rate1h > (13.44 * (1 - 0.995)) # burning through 2% of 28 days budget  within an hour
              AND
              slo_connector_data_failure_rate:ratio_rate5m > (13.44 * (1 - 0.995))
              )
              OR
              (
              slo_connector_data_failure_rate:ratio_rate6h > (5.6 * (1 - 0.995)) # burning through 5% of 28 days budget within 6 hours
              AND
              slo_connector_data_failure_rate:ratio_rate30m > (5.6 * (1 - 0.995))
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: 'High 1h/6h Connectors data budget burn for RHOC (current value: {{ $value | humanize }})'
            description: 'An error budget greater than 2% has been burnt in the last 1h/6h period'
            dashboard: 'https://grafana.app-sre.devshift.net/d/3lmqGVq7z/data-plane-overview?orgId=1'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/connectors_data_error_budget_burnt.adoc'

        - alert: RHOCConnectorsDataError2hTo24HOr6hTo3dBudgetBurn
          expr: |
            (
              slo_connector_data_failure_rate:ratio_rate24h > (2.8 * (1 - 0.995))
              AND
              slo_connector_data_failure_rate:ratio_rate2h > (2.8 * (1 - 0.995))
              )
              OR
              (
              slo_connector_data_failure_rate:ratio_rate3d > (0.93 * (1 - 0.995)) # burning through 10% of 28 days budget within 3 days
              AND
              slo_connector_data_failure_rate:ratio_rate6h > (0.93 * (1 - 0.995))
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: 'High 3d/24h Connectors data budget burn for RHOC (current value: {{ $value | humanize }})'
            description: 'An error budget greater than 10% has been burnt in the last 3 days period'
            dashboard: 'https://grafana.app-sre.devshift.net/d/3lmqGVq7z/data-plane-overview?orgId=1'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/connectors_data_error_budget_burnt.adoc'
