---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: cos-fleetshard-operator-camel-rules
spec:
  groups:
    - name: cos-fleetshard-operator-camel
      interval: 10m
      rules:
        - alert: CosFleetShardOperatorCamelTargetDown
          expr: group by (cluster_id) (up{container="cos-fleetshard-operator-camel"} !=1 or absent(up{container="cos-fleetshard-operator-camel"}))
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'the cos-fleetshard-operator-camel target is down'
            description: |
              prometheus has been unable to scrape the cos-fleetshard-operator-camel pod in the
              cluster: {{ $labels.cluster_id }} for longer than 10 minutes
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: CosFleetShardOperatorCamelContainerFrequentlyRestarting
          expr: sum by (cluster_id) (increase(kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel"}[60m])) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the cos-fleetshard-operator-camel pod is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: 'the cos-fleetshard-operator-camel operator container restarted frequently in the last 60 minutes'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
