---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: cos-fleetshard-operator-camel-rules
spec:
  groups:
    - name: cos-fleetshard-operator-camel
      interval: 10m
      rules:
        - alert: CosFleetShardOperatorCamelTargetDown
          expr: group by (cluster_id) (up{container="cos-fleetshard-operator-camel"} !=1 or absent(up{container="cos-fleetshard-operator-camel"}))
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the fleetshard-camel operator is down in cluster: {{ $labels.cluster_id }}
            description: |
              prometheus was unable to scrape the fleetshard-camel operator in the cluster: {{ $labels.cluster_id }} for longer than 10 minutes.
              This most likely means that the fleetshard-camel operator pod is unable to start
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: CosFleetShardOperatorCamelContainerFrequentlyRestarting
          expr: sum by (cluster_id) (increase(kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-camel"}[60m])) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the fleetshard-camel operator is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: |
              in the previous 60 minutes, the fleetshard-camel operator restarted frequently(more than 3 times)
              in cluster: {{ $labels.cluster_id }}
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
