---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: strimzi-cluster-operator-rules
spec:
  groups:
    - name: strimzi-cluster-operator
      interval: 10m
      rules:
        - alert: StrimziOperatorTargetDown
          expr: group by (cluster_id) (up{container="strimzi-cluster-operator"} !=1 or absent(up{container="strimzi-cluster-operator"}))
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'the strimzi-cluster-operator target is down'
            description: |
              prometheus has been unable to scrape the strimzi-cluster-operator pod in the
              cluster: {{ $labels.cluster_id }} for longer than 10 minutes
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: StrimziOperatorContainerFrequentlyRestarting
          expr: group by (cluster_id) (increase(kube_pod_container_status_restarts_total{container="strimzi-cluster-operator"}[60m]) > 3)
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the strimzi-cluster-operator pod is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: 'the strimzi-cluster-operator container restarted frequently in the last 60 minutes'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
