---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: strimzi-cluster-operator-rules
spec:
  groups:
    - name: strimzi-cluster-operator
      interval: 10m
      rules:
        - alert: StrimziOperatorTargetDown
          expr: group by (cluster_id) (up{container="strimzi-cluster-operator"} !=1 or absent(up{container="strimzi-cluster-operator"}))
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the debezium operator is down in cluster: {{ $labels.cluster_id }}
            description: |
              prometheus was unable to scrape the debezium operator in the cluster: {{ $labels.cluster_id }} for longer than 10 minutes.
              This most likely means that the debezium operator pod is unable to start
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: StrimziOperatorContainerFrequentlyRestarting
          expr: sum by (cluster_id) (increase(kube_pod_container_status_restarts_total{container="strimzi-cluster-operator"}[60m])) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the debezium operator is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: |
              in the previous 60 minutes, the debezium operator restarted frequently(more than 3 times)
              in cluster: {{ $labels.cluster_id }}
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
