apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tenant: rhoc
  name: cos-fleetshard-operator-debezium-rules
spec:
  groups:
    - name: cos-fleetshard-operator-debezium
      rules:
        - alert: CosFleetShardOperatorDebeziumTargetDown
          expr: up{container="cos-fleetshard-operator-debezium"} !=1 or absent(up{container="cos-fleetshard-operator-debezium"})
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: |
              the fleetshard-debezium operator is down
            description: |
              prometheus was unable to scrape the fleetshard-debezium operatorfor longer than 10 minutes.
              This most likely means that the fleetshard-debezium operator pod is unable to start
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
        - alert: CosFleetShardOperatorDebeziumContainerFrequentlyRestarting
          expr: increase(kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-debezium"}[60m]) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            the fleetshard-debezium operator is restarting frequently in cluster: {{ $labels.cluster_id }}
            description: |
              in the previous 60 minutes, the fleetshard-debezium operator restarted frequently(more than 3 times)
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-sre-sops/blob/main/sops/alerts/container_down.adoc'
