{
 "title": "Data Plane | Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connectors Requested (selected time)",
   "type": "bargauge",
   "description": "Total new Connectors requested vs the successful and the failure count within the selected time range.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((last_over_time(cos_fleetshard_sync_connector_state[$__range]) != 0) unless (cos_fleetshard_sync_connector_state offset $__range))",
     "legendFormat": "Connectors Created"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 1) unless cos_fleetshard_sync_connector_state offset $__range)",
     "legendFormat": "Successful"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 2) unless cos_fleetshard_sync_connector_state offset $__range)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 3) unless cos_fleetshard_sync_connector_state offset $__range)",
     "legendFormat": "Immediately Deleted"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 5) unless cos_fleetshard_sync_connector_state offset $__range)",
     "legendFormat": "Still Provisioning"
    }
   ]
  },
  {
   "title": "Requested Connectors Types (selected time)",
   "type": "piechart",
   "description": "Count of the types of Connectors requested on the selected time range.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cos_connector_type_id) ( (last_over_time(cos_fleetshard_sync_connector_state[$__range]) != 0) unless (cos_fleetshard_sync_connector_state offset $__range) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Clusters (selected time)",
   "type": "stat",
   "description": "Total unique Clusters in the selected time range.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster_id) (count_over_time(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Clusters",
   "type": "table",
   "description": "Table with the current clusters details.",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=~\".*_mctr-.*\"}"
    },
    {
     "expr": "count(up{container=\"integration\"}) by (cluster_id)"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "timeseries",
   "description": "Clusters count in the time series.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "count( count(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}) by (cluster_id) )",
     "legendFormat": "Clusters"
    }
   ]
  },
  {
   "title": "Total Namespaces (selected time)",
   "type": "stat",
   "description": "Total unique Namespaces in the selected time range.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (namespace) (count_over_time(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Namespaces",
   "type": "table",
   "description": "Table with the detail of the current name. Click on the namespace name to see the detailed view.",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=~\".*_mctr-.*\"}"
    },
    {
     "expr": "count(up{container=\"integration\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Total Namespaces",
   "type": "timeseries",
   "description": "Namespaces count in the time series.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "count( count(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}) by (namespace) )",
     "legendFormat": "Namespace"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Successful Connectors Count (selected time)",
   "type": "stat",
   "description": "Total Connectors, CamelK Connectors vs Debezium Connectors running in the selected time range.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 1)",
     "legendFormat": "Total Connectors"
    },
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state{cos_connector_type_id!~\"debezium-.*\"}[$__range]) == 1)",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state{cos_connector_type_id=~\"debezium-.*\"}[$__range]) == 1)",
     "legendFormat": "Debezium Connectors"
    }
   ]
  },
  {
   "title": "Successful Connectors Types",
   "type": "piechart",
   "description": "Count of the types of Connectors.",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cos_connector_type_id) (min_over_time(cos_fleetshard_sync_connector_state[$__range]) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectors Availability (selected time)",
   "type": "gauge",
   "description": "The percentage of time that the Connectors are available in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[$__range])) /\n( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[$__range])) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\"}[$__range])) ) ) * 100"
    }
   ]
  },
  {
   "title": "Connectors Running / Crashing / Stopped",
   "type": "timeseries",
   "description": "CamelK/Debezium Connectors crashing vs running \n vs stopped over time.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(cos_fleetshard_sync_connector_state == 2)",
     "legendFormat": "Crashing"
    },
    {
     "expr": "count(cos_fleetshard_sync_connector_state == 1)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(cos_fleetshard_sync_connector_state == 4)",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "CamelK Exchanges Count (selected time)",
   "type": "stat",
   "description": "Total, Completed, Failed, and Currently Inflight Exchanges for all the CamelK Connectors.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_total[$__range])) - sum(min_over_time(application_camel_context_exchanges_total[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total[$__range])) - sum(min_over_time(application_camel_context_exchanges_completed_total[$__range]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_failed_total[$__range])) - sum(min_over_time(application_camel_context_exchanges_failed_total[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count)",
     "legendFormat": "Inflight Currently"
    }
   ]
  },
  {
   "title": "CamelK Exchanges Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of exchanges completed in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n( sum(max_over_time(application_camel_context_exchanges_completed_total[$__range])) - sum(min_over_time(application_camel_context_exchanges_completed_total[$__range])) )\n/\n( sum(max_over_time(application_camel_context_exchanges_total[$__range])) - sum(min_over_time(application_camel_context_exchanges_total[$__range])) ) \n) * 100"
    }
   ]
  },
  {
   "title": "Number of CamelK Exchanges",
   "type": "timeseries",
   "description": "Exchanges Quantitative Information over time",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(application_camel_context_exchanges_completed_total)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Debezium Event Count (selected time)",
   "type": "stat",
   "description": "Total, Filtered, and Erroneous events seen for the  Debezium Connectors",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range]))",
     "legendFormat": "Total Events Seen"
    },
    {
     "expr": "sum(max_over_time(debezium_metrics_NumberOfEventsFiltered{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_NumberOfEventsFiltered{context=\"streaming\"}[$__range]))",
     "legendFormat": "Filtered Events"
    },
    {
     "expr": "sum(max_over_time(debezium_metrics_NumberOfErroneousEvents{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_NumberOfErroneousEvents{context=\"streaming\"}[$__range]))",
     "legendFormat": "Erroneous Events"
    }
   ]
  },
  {
   "title": "Debezium Events Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of events completed in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n( sum(max_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])))\n/\n( sum(max_over_time(debezium_metrics_SnapshotDurationInSeconds{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_SnapshotDurationInSeconds{context=\"streaming\"}[$__range])))\n) \n* 100"
    }
   ]
  },
  {
   "title": "Number of Debezium Events",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 33 },
   "targets": [
    {
     "expr": "sum(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"})",
     "legendFormat": "Total Events Seen"
    }
   ]
  }
 ]
}