{
 "title": "Data-plane SLO",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cos_fleetshard_sync_connector_state, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## Availability\n* This panel shows the 28 days and 7 days Availability for each individual Connector cluster, including the cluster id and SLO percentage.\n* Note that a Connector instance is evaluated for its availability only if it has been successfully configured and is able to startup once.\n* Can be filtered by Connector SLO percenatges, cluster Id and rolling window.\n* The SLO threshold is 99.5%, which is indicated by the horizontal red line.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n* You can click on an individual Connector cluster graph in the panel to get redirected to that cluster Dashboard."
   }
  },
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## Remaining Error Budget (Availability)\n* This panel shows the 28 days and 7 days Remaining Error Budgetfor each individual Connector cluster, including the cluster id.\n* Can be filtered by Remaining Error Budget percenatges, cluster Id and rolling window.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n* You can click on an individual Connector cluster graph in the panel to get redirected to that cluster Dashboard."
   }
  },
  {
   "title": "Availability - 28 days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) /\n( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) ) ) * 100",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Availability - 28 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) ) ) - sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) ) / ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) ) ) ) * 100, 0)",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Availability - 7 days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) /\n( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) ) ) * 100",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Availability - 7 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) ) ) - sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) ) / ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) ) ) ) * 100, 0)",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "options": {
    "content": "## Data Success Rate\n* This panel shows a 28 days and 7 days Exchanges Success rate for each individual Connector cluster, the cluster id and SLO percentage.\n* The rate is calculated using the data (sent or retrieved) to or from a third-party system.\n* Can be filtered by Connector SLO percenatges, cluster Id and rolling window.\n* The SLO threshold is 99.5%, which is indicated by the horizontal red line.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n* You can click on an individual Connector cluster graph in the panel to get redirected to that cluster Dashboard."
   }
  },
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "options": {
    "content": "## Remaining Error Budget (Data)\n* This panel shows the 28 days and 7 days Remaining Error Budget for each individual Connector cluster, including the cluster id.\n* Can be filtered by Remaining error budget percenatges, cluster Id and rolling window.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n* You can click on an individual Connector cluster graph in the panel to get redirected to that cluster Dashboard."
   }
  },
  {
   "title": "Data Success Rate - 28 days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n( sum(rate(application_camel_context_exchanges_completed_total{cluster_id=~\"$Cluster\"}[28d])) by (cluster_id)\n/\n sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) \n) * 100",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Data - 28 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( (sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) * 0.005) - sum(rate(application_camel_context_exchanges_failed_total{cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) ) / (sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[28d])) by (cluster_id) * 0.005) ) * 100, 0)",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Data Success Rate - 7 days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n( sum(rate(application_camel_context_exchanges_completed_total{cluster_id=~\"$Cluster\"}[7d])) by (cluster_id)\n/\n sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) \n) * 100",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Data - 7 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( (sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) * 0.005) - sum(rate(application_camel_context_exchanges_failed_total{cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) ) / (sum(rate(application_camel_context_exchanges_total{cluster_id=~\"$Cluster\"}[7d])) by (cluster_id) * 0.005) ) * 100, 0)",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  }
 ]
}