apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cos-fleetshard-debezium-metrics
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "cos-fleetshard-operator-debezium"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /q/metrics
      port: http
      metricRelabelings:
        - regex: endpoint|instance|job|namespace|receive|pod|prometheus
          action: labeldrop